import type { Config } from 'tailwindcss'
import tailor from '@tailwindcss/tailwind'

const config: Config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Light mode colors (from Cupertino Precision)
        surface: '#faf8fe',
        'surface-dim': '#dad9df',
        'surface-bright': '#faf8fe',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f8',
        'surface-container': '#eeedf3',
        'surface-container-high': '#e9e7ed',
        'surface-container-highest': '#e3e2e7',
        'on-surface': '#1a1b1f',
        'on-surface-variant': '#414753',
        inverseSurface: '#2f3034',
        'inverse-on-surface': '#f1f0f5',
        outline: '#717785',
        'outline-variant': '#c1c6d6',
        'surface-tint': '#005cbb',
        primary: '#0059b5',
        'on-primary': '#ffffff',
        'primary-container': '#0071e3',
        'on-primary-container': '#fcfbff',
        inversePrimary: '#abc7ff',
        secondary: '#5f5e60',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2dfe1',
        'on-secondary-container': '#636264',
        tertiary: '#9b3f00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c25100',
        'on-tertiary-container': '#fffaf9',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#abc7ff',
        'on-primary-fixed': '#001b3f',
        'on-primary-fixed-variant': '#00458f',
        'secondary-fixed': '#e4e2e4',
        'secondary-fixed-dim': '#c8c6c8',
        'on-secondary-fixed': '#1b1b1d',
        'on-secondary-fixed-variant': '#474649',
        'tertiary-fixed': '#ffdbcb',
        'tertiary-fixed-dim': '#ffb693',
        'on-tertiary-fixed': '#341000',
        'on-tertiary-fixed-variant': '#7a3000',
        background: '#faf8fe',
        'on-background': '#1a1b1f',
        'surface-variant': '#e3e2e7',
        // Additional Apple colors
        label: '#86868B',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.125rem',
        space-xs: '0.25rem',
        space-sm: '0.5rem',
        space-md: '0.75rem',
        space-base: '1rem',
        space-lg: '1.25rem',
        space-xl: '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '2.5rem',
        'space-4xl': '3rem',
        'space-5xl': '4rem',
        'space-6xl': '6rem',
        'gutter-mobile': '1rem',
        'gutter-tablet': '1.5rem',
        'gutter-desktop': '2rem',
        'margin-mobile': '1.25rem',
        'margin-tablet': '2rem',
        'margin-desktop': '4rem',
      },
      boxShadow: {
        card: '0 4px 20px rgba(0, 0, 0, 0.03), 0 1px 3px rgba(0, 0, 0, 0.02)',
        popover: '0 12px 40px rgba(0, 0, 0, 0.08), 0 4px 12px rgba(0, 0, 0, 0.04)',
        input: '0 1px 2px rgba(0, 0, 0, 0.05)',
      },
      transitionTimingFunction: {
        cubic: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [tailor()],
}
export default config