export const NOTIFICATIONS_100 = [
  "Someone new could be waiting to meet you.",
  "Your next connection might be one tap away.",
  "Say hello to someone interesting today.",
  "New people, new conversations, new possibilities.",
  "Start a conversation. You never know where it leads.",
  "Your next great conversation could start today.",
  "Make someone smile with a simple “Hi.”",
  "Someone interesting might be online right now.",
  "Ready to discover someone new?",
  "It’s a great time to start a conversation.",
  "Good morning! A new connection awaits.",
  "New day. New people. New possibilities.",
  "Start your morning with a great conversation.",
  "Make today a day to remember.",
  "Good morning! Who will you connect with today?",
  "Your next conversation could begin this morning.",
  "Fresh day, fresh connections.",
  "Start your day with a little social energy.",
  "Someone new could brighten your day.",
  "Wake up, connect, and discover.",
  "Bored this afternoon? Meet someone new.",
  "Take a break and start a conversation.",
  "See who’s around on AnvioTalk.",
  "Your afternoon could use a new connection.",
  "Turn your free time into connection time.",
  "A quick chat can make your day better.",
  "Someone interesting may be just a tap away.",
  "Take the first step. Say hello.",
  "Discover someone worth talking to.",
  "Today’s goal: Start one great conversation.",
  "Evening is here. Ready to connect?",
  "Make your evening a little more interesting.",
  "End your day with a great conversation.",
  "Relax, connect, and discover someone new.",
  "Good vibes and great conversations await.",
  "Who knows who you might meet tonight?",
  "Don’t let your evening be boring.",
  "Someone interesting could be online tonight.",
  "Your next “Hi” could be the start of something great.",
  "Make tonight a night to remember.",
  "Still awake? Someone might be waiting to chat.",
  "End your day with a meaningful conversation.",
  "Late-night conversations hit different.",
  "One more conversation before you sleep?",
  "Your night could use a little connection.",
  "Someone might be happy to hear from you tonight.",
  "Good night! See you on AnvioTalk tomorrow.",
  "One last look at your connections?",
  "Night vibes are better with good company.",
  "Your next memorable conversation could start tonight.",
  "Ready to meet someone special?",
  "Great connections start with simple conversations.",
  "Your special someone could be closer than you think.",
  "Give a new connection a chance.",
  "Sometimes one conversation changes everything.",
  "Discover chemistry through conversation.",
  "One chat could become a beautiful story.",
  "Your next chapter could start with a “Hi.”",
  "Follow your heart. Start a conversation.",
  "Maybe today is your lucky day.",
  "New stories are waiting for you.",
  "Don’t miss today’s stories!",
  "See what people are sharing today.",
  "Something interesting might be on your feed.",
  "Fresh stories. Fresh vibes.",
  "See a story you like? Start a conversation.",
  "Your feed might have something interesting today.",
  "Discover what’s happening on AnvioTalk.",
  "Have you checked today’s stories?",
  "New stories. New people. New possibilities.",
  "We haven’t seen you in a while!",
  "AnvioTalk missed you. Come back and connect.",
  "Someone interesting could be waiting for you.",
  "There may be something new waiting for you.",
  "It’s been a while. See what you’ve missed.",
  "Your next connection won’t happen if you stay away.",
  "Missed AnvioTalk? Come back and say hello.",
  "Come back and discover new people.",
  "Your next great conversation might be waiting.",
  "Come back. Your connections are still here.",
  "Make one new connection today.",
  "Message someone you’d like to know better.",
  "Don’t be afraid to make the first move.",
  "Great conversations create great connections.",
  "Be yourself. The right people will notice.",
  "Don’t just scroll. Connect!",
  "Meet someone new today.",
  "One “Hi” can start something amazing.",
  "Real connections start with real conversations.",
  "Your challenge today: One meaningful conversation.",
  "Psst… someone interesting might be online!",
  "We have a feeling you should check AnvioTalk.",
  "Connection vibes are strong today!",
  "Bored? We know what you can do.",
  "Less scrolling. More connecting.",
  "Make someone’s day with a simple hello.",
  "Ready? Let’s connect!",
  "In the mood to chat? AnvioTalk is ready.",
  "Maybe today you’ll meet someone worth knowing.",
  "AnvioTalk is calling — your next connection awaits!"
];
